language: elixir

elixir:
  - 1.8.1

otp_release:
  - 20.3

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix format --check-formatted
  - mix coveralls.travis --pro
  - mix credo

branches:
  only:
    - master
